project:
  type: website
  output-dir: docs
  resources:
   - .nojekyll

  

website:
  title: "PPOL 5203 - Data Science I: Foundations"
  sidebar:
    background: light
    logo: "images/logo_gtown.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/TiagoVentura/ppol5203
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: course_infrastructure.qmd
        text: Course Tech Info
      #- href: problemset.qmd
      #  text: Problem Sets
      - href: finalproject.qmd
        text: Final Project
      - section: "Materials"
        contents: 
          - href: weeks/week-01.qmd
            text: "Week 1: Intro"
          - href: weeks/week-02.qmd
            text: "Week 2: Version Control"
          - href: weeks/week-03.qmd
            text: "Week 3: Intro to Python "
          - href: weeks/week-04.qmd
            text: "Week 4: Intro to Python II"
          - href: weeks/week-05.qmd
            text: "Week 5: From Nested lists to Dataframes"
          - href: weeks/week-06.qmd
            text: "Week 6: Pandas II"
          - href: weeks/week-07.qmd
            text: "Week 7: Joinining, Tidying and Visualizing Data"
          - href: weeks/week-08.qmd
            text: "Week 8: Scraping + APIs"
          #- href: weeks/week-09.qmd
          #  text: "Week 9: APIs + Selenium"
          #- href: weeks/week-10.qmd
          #  text: "Week 9: Statistical Learning"
          #- href: weeks/week-11.qmd
          #  text: "Week 11: Text as Data"
          # - href: weeks/week-12.qmd
          #  text: "Week 12: Text as Data II"
          # - href: weeks/week-13.qmd
          #  text: "Week 13: SQL"
          # - href: weeks/week-14.qmd
          #  text: "Week 14: Project Presentation"
          
          
      
format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

